api = "0.10"

[buildpack]
id = "malax/ollama"
version = "1.0.0"
name = "Ollama Buildpack"
homepage = "https://github.com/malax/buildpack-ollama"
description = "Builds an OCI image with Ollama and a large language model."
keywords = ["ollama", "ai", "llm"]

[[buildpack.licenses]]
type = "BSD-3-Clause"

[[targets]]
arch = "amd64"
os = "linux"

[[targets]]
arch = "arm64"
os = "linux"

# https://github.com/buildpacks/pack/issues/2047
[[stacks]]
id = "*"

[metadata]
ollama_version = "0.1.48"
amd64_download_url = "https://github.com/ollama/ollama/releases/download/v0.1.48/ollama-linux-amd64"
arm64_download_url = "https://github.com/ollama/ollama/releases/download/v0.1.48/ollama-linux-arm64"
